# Generated by Django 4.1.6 on 2023-03-02 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credential',
            name='user',
        ),
        migrations.AddField(
            model_name='credential',
            name='cohesive_instance_id',
            field=models.CharField(default='null', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='credential',
            name='cohesive_user_id',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='credential',
            name='cohesive_user_name',
            field=models.CharField(default='null', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='credential',
            name='cohesive_workspace_id',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='credential',
            name='cohesive_workspace_name',
            field=models.CharField(default='null', max_length=300),
            preserve_default=False,
        ),
    ]
