# Generated by Django 4.1.6 on 2023-03-02 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youtube_auth', '0002_remove_credential_user_and_more'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='scheduled_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='youtube_auth.credential'),
        ),
    ]
